language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
  - php: hhvm

cache:
  apt: true
  directories:
    - tests/node/node_modules
    - $HOME/.composer/cache

install:
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
